### ISSUE TITLE
Plus/Min buttons are not working in Cart section

### ISSUE THREAD

**Issue by anebi** [nielslange/smntcs-woocommerce-quantity-buttons#1]
Hi,

I installed your plugin and I am really happy with it. I noticed that +/- works only for single product. JS catch events for single products only, but it would be great if you update the code so it can catch also +/- events on cart section, because +/- buttons appear there too when we activate the plugin.

Thanks in advance,
Ali Nebi

**Comment by nielslange** [comment]
@anebi Shame on me! 🤭I just saw your comment. The issue should have been fixed with https://github.com/nielslange/smntcs-woocommerce-quantity-buttons/commit/f02330d697c7ede8f9066ae9fc41296978ff4819. I'll mark this issue as closed now, but please let me know if the issue still occurs on your end.

**Comment by anebi** [comment]
Hi, thanks for update and applied fix. Yeah, i did fix it manually on my side long time ago :)

Regards,
Ali

**Comment by nielslange** [comment]
@anebi I'm glad to hear that you've fixed it and that it's working as expected now. I have to admit that I monitored the tickets in Github as I usually receive comments via https://wordpress.org/support/plugin/smntcs-woocommerce-quantity-buttons/. Thus, record to myself: _"Keep an eye on Github issues as well!"_ 😉
