### ISSUE TITLE
Minus/Plus not working on product page

### ISSUE THREAD

**Issue by Celecis** [nielslange/smntcs-woocommerce-quantity-buttons#16]
Hi, Could you help me please?
I installed this plugin and it works fine on the cart page, but not on a product page.
Could you try and help me figure out why? If it is ur plugins problem or another one?
I am using: 
WooCommerce Min Max Quantity & Step Control Single
&
WooCommerce Variations In Table:
https://jbartes.pt/produto/tinta-acrilica-20ml-metalica/

It has a min quantity set to 6, maximum is empty and step is 6.
When you click on the minus button or the plus button, it doesn't do anything.
BUT if you go to the cart page, it works fine.

Thank you.

**Comment by nielslange** [comment]
@Celecis I can not access your site at the moment. It seems to be under construction. Are you able to deactivate all plugins, except mine, to see if the issue still appears on your end? If the issue does not appear, what I expect, then please activate all other plugins one by one and check if the functionality is broken after every plugin you’ve activated.

Please let me know if this does not solve the issue for you.

**Comment by Celecis** [comment]
Hi Niels, the problemn was with the table view I was using with another’s
plugin. The plugin owner helped me and all is fixed! If u want to know the
plugin that interferes with urs, it’s
Woocommerce Variations Im Table.

Regards,
Vanessa.


Niels Lange <notifications@github.com> escreveu em sáb, 11/01/2020 às 10:33
:

**Comment by nielslange** [comment]
Hello Vanessa 👋

I'm glad to hear that the issue is fixed. As the issue was caused by another plugin, I guess there's nothing I need to adjust on my end. Have you asked the developers of the other plugin to apply the fix they offered you also in their plugin to make it compatible to mine and potentially other plugins as well? If not, I'd do that to help them to grow. 😀

**Comment by nielslange** [comment]
Closed based on https://github.com/nielslange/smntcs-woocommerce-quantity-buttons/issues/16#issuecomment-573321990
