### ISSUE TITLE
add different unit (0.5) instead (1) - error

### ISSUE THREAD

**Issue by ofer777** [nielslange/smntcs-woocommerce-quantity-buttons#19]
Hi,
Im trying to use Advanced Product Quantity (https://woocommerce.com/products/advanced-product-quantity) so I can use half unit (0.5) and not (1) but its not function and its not responsive as it should.
<img width="542" alt="Screenshot 2020-03-29 at 18 52 47" src="https://user-images.githubusercontent.com/46934496/77853752-7eb27080-71ee-11ea-9734-92a75316e910.png">

**Comment by nielslange** [comment]
@ofer777 I just tested the plugin _SMNTCS WooCommerce Quantity Buttons_ with the plugin _Advanced Product Quantity_. The issue that you are facing is not caused by _SMNTCS WooCommerce Quantity Buttons_, but by _Advanced Product Quantity_. Only natural numbers (0, 1, 2, etc.) can be used as minimum respectively maximum quantity. You could suggest this enhancement via https://woocommerce.com/my-account/create-a-ticket/.

**Comment by ofer777** [comment]
Hi Niels,

Thanks for the reply!

No its not true - I switch off the SMNTCS plugin and it's working perfect without it - I keep it off so you can check it.

Best Regards, Ofer





________________________________

**Comment by nielslange** [comment]
When deactivating the plugin _SMNTCS WooCommerce Quantity Buttons_, I'm still unable to add rational numbers as seen on

![Screen Shot on 2020-03-30 at 15-22-36](https://user-images.githubusercontent.com/3323310/77891208-d27a9380-729a-11ea-84d4-39cd148e6151.png)

**Comment by ofer777** [comment]
Hi Niels,

The minimum have to be 1,2 ...

but I talk about the step number to be 0.5 not the minimum

Best Regards, Ofer





________________________________

**Comment by nielslange** [comment]
Thanks for clarifying this, @ofer777. I’ll look up this issue.

**Comment by ofer777** [comment]
Thanks 😊

**Comment by nielslange** [comment]
@ofer777 In my case, the step number also cannot be a rational number:

![Screen Shot on 2020-03-30 at 20-32-10](https://user-images.githubusercontent.com/3323310/77918192-bdffc080-72c5-11ea-827b-dcfa4c864e6e.png)

Are you using the latest and original version of [Advanced Product Quantity](https://woocommerce.com/products/advanced-product-quantity)? I downloaded that plugin earlier today and for none of the fields I am able to add 0.5 as a value.

Also, purchasing half of a product does not really make sense. If you handle weight- or volume-based products, I'd rather adjust the scale. Thus, instead of selling `0.5 l` resp. `0.5 kg` you could sell `500 ml` resp. `500 g`.

**Comment by ofer777** [comment]
Hi Niels,

Sorry for delay, you right - I use different version ….

- Any way I'm trying to use different plug in but still the some issue ( https://wordpress.org/plugins/wpc-product-quantity )
- as I did the Update today it seems to be new bug that show “0” in the cart.

**Comment by nielslange** [comment]
https://wordpress.org/plugins/wpc-product-quantity is overwriting the same WooCommerce template `quantity-input.php` as my plugin and when activating both plugin, I can only see their template. I'm afraid, that's nothing I can adjust on my end due to the nature of how these two plugins had been developed.

**Comment by ofer777** [comment]
Thanks... any news about the new issue with tho “0” on the cart?

**Comment by nielslange** [comment]
Can you send me the WooCommerce System Status Report of your site as described on https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/, so that I see what plugins you are using? When testing the plugin against WooCommerce only, I do not see 0 but 1.

**Comment by ofer777** [comment]
Can I send you my log in detail?

**Comment by nielslange** [comment]
Do you trust me? 😁 Joke aside, I'd prefer if you simply post your WooCommerce System Status Report. Imagine you sent me your credentials and someone hacks your site. It would be easy to think that I tempered with your site. That said, if you post your WooCommerce System Status Report I'll should be able to investigate this issue. 

Also, have you tried deactivating all plugins except _SMNTCS WooCommerce Quantity Buttons_
and _WooCommerce_ to see how the plugin behaves when being isolated?

**Comment by ofer777** [comment]
Hi Niels,
I trust you 😊

Yes, I did test it - the only plugin is active its:

- Elementor
- Elementor pro
- WooCommerce
- SMNTCS

`
### WordPress Environment ###

WordPress address (URL): http://we-perfect.com
Site address (URL): http://we-perfect.com
WC Version: 4.0.1
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.14
Action Scheduler Version: ✔ 3.1.4
WC Admin Version: ✔ 1.0.3
Log Directory Writable: ✔
WP Version: 5.4
WP Multisite: –
WP Memory Limit: 756 MB
WP Debug Mode: –
WP Cron: ✔
Language: he_IL
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.14
PHP Post Max Size: 128 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.62.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.47-cll-lve
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.0.1
WC Database Prefix: wp_
הגודל הכולל של בסיס הנתונים: 158.81MB
גודל הנתונים של בסיס הנתונים: 157.23MB
גודל האינדקס של בסיס הנתונים: 1.58MB
wp_woocommerce_sessions: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_woocommerce_api_keys: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_woocommerce_attribute_taxonomies: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_woocommerce_downloadable_product_permissions: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_woocommerce_order_items: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_woocommerce_order_itemmeta: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע MyISAM
wp_woocommerce_tax_rates: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_woocommerce_tax_rate_locations: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_woocommerce_shipping_zones: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_woocommerce_shipping_zone_locations: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_woocommerce_shipping_zone_methods: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_woocommerce_payment_tokens: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_woocommerce_payment_tokenmeta: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_woocommerce_log: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_actionscheduler_actions: נתונים: 0.49MB + אינדקס: 0.14MB + מנוע MyISAM
wp_actionscheduler_claims: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_actionscheduler_groups: נתונים: 0.00MB + אינדקס: 0.01MB + מנוע MyISAM
wp_actionscheduler_logs: נתונים: 0.23MB + אינדקס: 0.20MB + מנוע MyISAM
wp_commentmeta: נתונים: 0.00MB + אינדקס: 0.01MB + מנוע MyISAM
wp_comments: נתונים: 0.01MB + אינדקס: 0.01MB + מנוע MyISAM
wp_cp_calculated_fields_form_discount_codes: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_cp_calculated_fields_form_posts: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_cp_calculated_fields_form_revision: נתונים: 0.01MB + אינדקס: 0.00MB + מנוע MyISAM
wp_cp_calculated_fields_form_settings: נתונים: 0.01MB + אינדקס: 0.00MB + מנוע MyISAM
wp_failed_jobs: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_links: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_mailchimp_carts: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_mailchimp_jobs: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_mp_additional_info: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
wp_mp_articles: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
wp_mp_article_category: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
wp_mp_bookings: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
wp_mp_cities: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
wp_mp_distance: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
wp_mp_elevator: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
wp_mp_email_templates: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
wp_mp_floors: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
wp_mp_movesize: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
wp_mp_order_client_info: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
wp_mp_packaging_unpackagin: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
wp_mp_pricing_rules: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
wp_mp_room_type: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
wp_mp_schedule_dayoffs: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
wp_mp_sms_templates: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
wp_ms_snippets: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_nobuna_backups: נתונים: 0.00MB + אינדקס: 0.01MB + מנוע MyISAM
wp_nobuna_downloads: נתונים: 0.00MB + אינדקס: 0.01MB + מנוע MyISAM
wp_nobuna_products: נתונים: 0.01MB + אינדקס: 0.00MB + מנוע MyISAM
wp_options: נתונים: 2.27MB + אינדקס: 0.25MB + מנוע MyISAM
wp_postmeta: נתונים: 64.52MB + אינדקס: 0.55MB + מנוע MyISAM
wp_posts: נתונים: 89.22MB + אינדקס: 0.16MB + מנוע MyISAM
wp_queue: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_snippets: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_termmeta: נתונים: 0.00MB + אינדקס: 0.01MB + מנוע MyISAM
wp_terms: נתונים: 0.00MB + אינדקס: 0.01MB + מנוע MyISAM
wp_term_relationships: נתונים: 0.00MB + אינדקס: 0.01MB + מנוע MyISAM
wp_term_taxonomy: נתונים: 0.00MB + אינדקס: 0.01MB + מנוע MyISAM
wp_tm_taskmeta: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_tm_tasks: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_usermeta: נתונים: 0.03MB + אינדקס: 0.02MB + מנוע MyISAM
wp_users: נתונים: 0.00MB + אינדקס: 0.01MB + מנוע MyISAM
wp_wc_admin_notes: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_wc_admin_note_actions: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_wc_category_lookup: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_wc_customer_lookup: נתונים: 0.00MB + אינדקס: 0.01MB + מנוע MyISAM
wp_wc_download_log: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_wc_order_coupon_lookup: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_wc_order_product_lookup: נתונים: 0.00MB + אינדקס: 0.01MB + מנוע MyISAM
wp_wc_order_stats: נתונים: 0.00MB + אינדקס: 0.01MB + מנוע MyISAM
wp_wc_order_tax_lookup: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_wc_product_meta_lookup: נתונים: 0.00MB + אינדקס: 0.01MB + מנוע MyISAM
wp_wc_tax_rate_classes: נתונים: 0.00MB + אינדקס: 0.01MB + מנוע MyISAM
wp_wc_webhooks: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_woocommerce_shipping_table_rates: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_yith_wccl_meta: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_yoast_seo_links: נתונים: 0.02MB + אינדקס: 0.01MB + מנוע MyISAM
wp_yoast_seo_meta: נתונים: 0.07MB + אינדקס: 0.08MB + מנוע MyISAM

### Post Type Counts ###

attachment: 100
custom_css: 1
customize_changeset: 22
elementor_library: 22
nav_menu_item: 5
page: 17
post: 1
product: 18
product_variation: 16
revision: 1479
shop_order: 9

### Security ###

Secure connection (HTTPS): ❌
החנות לא משתמשת בHTTPS. מידע נוסף על HTTPS ותעודות SSL.
Hide errors from visitors: ✔

### Active Plugins (4) ###

אלמנטור פרו: מאת Elementor.com<http://Elementor.com> – 2.9.2
אלמנטור: מאת Elementor.com<http://Elementor.com> – 2.9.7
SMNTCS WooCommerce Quantity Buttons: מאת Niels Lange  – 1.14 – הפריט לא נבדק עם גרסה פעילה של WooCommerce
ווקומרס: מאת חברת אוטומטיק – 4.0.1

### Inactive Plugins (39) ###

Accessibility by UserWay: מאת UserWay.org<http://UserWay.org> – 1.2
Astra Pro: מאת Brainstorm Force – 2.3.3
Autoptimize: מאת Frank Goossens (futtta) – 2.6.2
Code Snippets: מאת Code Snippets Pro – 2.14.0
Facebook for WooCommerce: מאת Facebook – 1.10.2
Insert Headers and Footers: מאת WPBeginner – 1.4.5
Jetpack by WordPress.com<http://WordPress.com>: מאת Automattic – 8.3
Limit Login Attempts Reloaded: מאת WPChef – 2.10.1
Loco Automatic Translate Addon: מאת Cool Plugins – 1.7
Loco Translate: מאת Tim Whitlock – 2.3.1
Mailchimp for WooCommerce: מאת Mailchimp – 2.3.5
Nobuna Plugins: מאת Nobuna – 2.6
Really Simple SSL: מאת Rogier Lankhorst
Mark Wolters – 3.3

SVG Support: מאת Benbodhi – 2.3.17
Tidio Chat: מאת Tidio Ltd. – 4.2.1
WooCommerce - ShipStation Integration: מאת WooCommerce – 4.1.34
WooCommerce Admin: מאת WooCommerce – 1.0.3
WooCommerce Advanced Quantity: מאת Morning Train Technologies ApS – 2.4.5 – הפריט לא נבדק עם גרסה פעילה של WooCommerce
WooCommerce Cost of Goods: מאת SkyVerge – 2.9.5
WooCommerce Custom Fields for Variations by Iconic: מאת Iconic – 1.2.3 – הפריט לא נבדק עם גרסה פעילה של WooCommerce
WooCommerce Measurement Price Calculator: מאת SkyVerge – 3.17.3
WooCommerce Min/Max Quantities: מאת WooCommerce – 2.4.15
WooCommerce Min Max Quantity & Step Control Single: מאת Saiful Islam – 1.6 – הפריט לא נבדק עם גרסה פעילה של WooCommerce
WooCommerce Order Delivery: מאת WooCommerce – 1.6.4 – 1.6.5 זמין – הפריט לא נבדק עם גרסה פעילה של WooCommerce
WooCommerce PayPal Checkout Gateway: מאת WooCommerce – 1.6.20 – הפריט לא נבדק עם גרסה פעילה של WooCommerce
WooCommerce Services: מאת Automattic – 1.22.5
WooCommerce Shipment Tracking: מאת WooCommerce – 1.6.19
WooCommerce Ship to Multiple Addresses: מאת WooCommerce – 3.6.15 – 3.6.16 זמין
WooCommerce Stripe Gateway: מאת WooCommerce – 4.3.2 – הפריט לא נבדק עם גרסה פעילה של WooCommerce
WooCommerce Table Rate Shipping: מאת WooCommerce – 3.0.22
WPC Product Bundles for WooCommerce: מאת WPClever.net<http://WPClever.net> – 4.0.2
WPC Product Quantity for WooCommerce: מאת WPClever.net<http://WPClever.net> – 1.2.1
WPC Product Tabs for WooCommerce: מאת WPClever.net<http://WPClever.net> – 1.0.7
WPC Variations Radio Buttons for WooCommerce: מאת WPClever.net<http://WPClever.net> – 2.0.0
WP Rocket: מאת WP Media – 3.5.0.4
YITH WooCommerce Color and Label Variations Premium: מאת YITH – 1.10.1 – הפריט לא נבדק עם גרסה פעילה של WooCommerce
YITH WooCommerce Minimum Maximum Quantity Premium: מאת YITH – 1.4.7
YITH WooCommerce Product Countdown Premium: מאת YITH – 1.4.0
Yoast SEO: מאת Team Yoast – 13.4

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (1) ###

installatron_hide_status_test.php: מאת  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: ILS (₪)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com<http://WooCommerce.com>: ✔

### WC Pages ###

בסיס חנות: #6 - /shop/
עגלת קניות: #7 - /cart/
תשלום: #8 - /checkout/
החשבון שלי: #9 - /my-account/
תנאי שימוש: #3 - /privacy-policy/

### Theme ###

Name: Astra
Version: 2.3.4
Author URL: https://wpastra.com/about/
Child Theme: ❌ – אם משנים את ווקומרס בערכת נושא אב שלא נבנתה באופן אישי
מומלץ להשתמש בערכת עיצוב בת. אפשר לראות: כיצד ליצור ערכת עיצוב בת

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

הושלם: 1,356
Oldest: 2020-03-01 12:15:44 +0000
Newest: 2020-04-01 12:11:25 +0000

ממתין לאישור: 2
Oldest: 2020-04-01 13:04:09 +0000
Newest: 2020-04-01 13:04:09 +0000

`




Regards,

Ofer Hai

On 1 Apr 2020, at 14:05, Niels Lange <notifications@github.com<mailto:notifications@github.com>> wrote:


Do you trust me? 😁 Joke aside, I'd prefer if you simply post your WooCommerce System Status Report. Imagine you sent me your credentials and someone hacks your site. It would be easy to think that I tempered with your site. That said, if you post your WooCommerce System Status Report I'll should be able to investigate this issue.

Also, have you tried deactivating all plugins except SMNTCS WooCommerce Quantity Buttons
and WooCommerce to see how the plugin behaves when being isolated?

**Comment by nielslange** [comment]
I just deployed a new version with an integrated check. Can you tell me if the issue is solved for you due to the release?

**Comment by ofer777** [comment]
Its fixed :)))

Would you try to fix it to work with any plugin that give you to add 0.5 unit for step?

**Comment by nielslange** [comment]
> Its fixed :)))

Yeah. I'm glad to hear that! 😀

> Would you try to fix it to work with any plugin that give you to add 0.5 unit for step?

Sure. I'll look up this issue as well and will adjust the plugin accordingly. This might take a few days thought as I'm currently testing all my plugins against the recent WordPress 5.4 release.

**Comment by ofer777** [comment]
Thanks 🙏🏻 😊

**Comment by ofer777** [comment]
Hi Niels,

How are you?

Any news about the "Would you try to fix it to work with any plugin that give you to add 0.5 unit for step?”

- Also I found a top line of shadow on the top of the number (mobile only) - please see pic

**Comment by nielslange** [comment]
> Any news about the "Would you try to fix it to work with any plugin that give you to add 0.5 unit for step?”

Hello @ofer777 👋 I'm afraid, I won't be able to fix this issue as I'm unable to reproduce this issue on my end. As the plugin _WPC Product Quantity for WooCommerce_ overwrites the same WooCommerce template as my plugin, I can either have my plugin activated or theirs but not both simultaneously. Therefore, it's not possible to fix this issue due to technical reasons.

**Comment by ofer777** [comment]
Thanks for the quick reply :)

- Also I found a top line of shadow on the top of the number (mobile only) - please see pic
[cid:826FB58B-352F-46F2-B67A-2448FB4F1DB7]

**Comment by nielslange** [comment]
When replying via email, the image will not be moved into GitHub. Please head over to https://github.com/nielslange/smntcs-woocommerce-quantity-buttons/issues/19 directly to upload the image there.

**Comment by ofer777** [comment]
![IMG_0871](https://user-images.githubusercontent.com/46934496/79391208-cb7da180-7f79-11ea-8b7a-94cc9f154f46.png)

**Comment by ofer777** [comment]
![IMG_0871](https://user-images.githubusercontent.com/46934496/79391370-18617800-7f7a-11ea-983d-c0fe5b21e0ba.png)
