### ISSUE TITLE
Add compatibility for grouped products

### ISSUE THREAD

**Issue by nielslange** [nielslange/smntcs-woocommerce-quantity-buttons#21]
Reported in https://wordpress.org/support/topic/input-value-incorrect/#post-12604475:

> If min value is 0 like with grouped products no value is shown at all and buttons don’t work untill u manually insert a value.
> 
> I solved it by changing inside quantity-input.php;
> 
> `value="<?php echo esc_attr( $input_value ); ?>"`
> 
> to
> 
> `value="<?php echo esc_attr( $min_value ); ?>"`
> 
> After this change simple and grouped products both work as expected.
> 
> Using latest woocommerce and plugin..
> 
> Please change it in future update

**Comment by nielslange** [comment]
See https://wordpress.org/support/topic/input-value-incorrect/#post-12604475

**Comment by Jeroenleender** [comment]
after updatting to 1.15 the problem is back....

**Comment by nielslange** [comment]
> after updatting to 1.15 the problem is back....

Damn it! 🤦‍♂ Sorry for that, @Jeroenleender. I wasn't able to reproduce this issue in the first place and thought that with 1.14 it would be fixed, which apparently it was. However, 1.14 seem to break functionality for non-grouped products. That's why I deployed 1.1.5. 

The issue that you are facing is that when using grouped products, no quantity is visible at all, right?

**Comment by Jeroenleender** [comment]
When u open a grouped product and get an overview of simple products, the default value should be 0.
Your current option can't handle zero values so it won't show any number. + and - buttons don't work then untill u add a number yourself as a value.

**Comment by Jeroenleender** [comment]
When i use my fix all my grouped and simple products work correctly.
I can't test variable products tho.

**Comment by nielslange** [comment]
That's good to know. Thus, I need to figure out how to detect whether a product is a grouped product. If so, handle the logic of 1.14, otherwise handle the logic of 1.1.3 resp. 1.1.5. Shouldn't be too complicated to implement. Sorry for the inconvenience caused by the latest release, though. For the time being, you could use [WP Rollback](https://wordpress.org/plugins/wp-rollback/) to rollback my plugin to the previous version until I release 1.16.

**Comment by Jeroenleender** [comment]
if( $product->is_type( 'simple' ) )
since they are simple products would work, but this also effects normal simple products.
So i think what would be better is to check the array and see if something matches like child parent connection that doesnt include normal simple products.

For myself i just used he former fix on the latest patch since that also works

**Comment by Jeroenleender** [comment]
or maybe something like this.....

`if( $product->is_type( 'simple' )  && $input_value == '' )`
