### ISSUE TITLE
Double Steps

### ISSUE THREAD

**Issue by sushiel** [nielslange/smntcs-woocommerce-quantity-buttons#32]
When using the + or - buttons, the quantity jumps 2 steps.
How can this be resolved?

**Comment by nielslange** [comment]
@sushiel Are you using any additional plugins or have you added any custom code that might lead to this issue? By default, the plugin does not change the step sequence.

**Comment by nielslange** [comment]
Hello @sushiel 👋 As I haven't heard back from you, I'm going to close this issue for now.
