### ISSUE TITLE
Cannot add more then 1 item on the front/shop page

### ISSUE THREAD

**Issue by ofer777** [nielslange/smntcs-woocommerce-quantity-buttons#60]
I can only add items on the first product but all the other not respond to the buttons 
<img width="1218" alt="Screen Shot 2020-12-22 at 19 27 45" src="https://user-images.githubusercontent.com/46934496/102916304-0088af00-448c-11eb-87be-105d9977da53.png">

**Comment by ofer777** [comment]
Hi, would you please response on the subject - thanks a lot

**Comment by nielslange** [comment]
Hello @ofer777: I just release version 1.24 and the buttons should now work as expected on all pages.
