### ISSUE TITLE
[BUG] Not working properly on cart page

### ISSUE THREAD

**Issue by meirroth** [nielslange/smntcs-woocommerce-quantity-buttons#63]
On cart page there are two issues:
1. Can't update cart after changing product quantity.
2. If there is more than one product in the cart, the +/- buttons only work on the first product row.

Thanks.

**Comment by Stan801003A** [comment]
I am having the same issue

**Comment by meirroth** [comment]
I have looked into the code, 
First, this plugin was not been updated to the latest version of woo and WP, and the template that this plugin is overriding (quantity-input.php) was updated by woo.
secondly, the JavaScript code for the qty buttons does not deal with more then one instance of the buttons on one page.

**Comment by ofer777** [comment]
I am having the same issue

**Comment by nielslange** [comment]
@meirroth, @Stan801003A & @ofer777: I just release version 1.24 and the buttons should now work as expected on all pages.
