### ISSUE TITLE
not working in product page but work in basket!!

### ISSUE THREAD

**Issue by icepunk** [nielslange/smntcs-woocommerce-quantity-buttons#69]
not working in product page ( [here](https://maghaaze.pejman.foundation/product/in-the-midst-vol-1-ticket/) ) but work in basket!!
its was working fine before.

**Comment by icepunk** [comment]
i also test this way:
https://github.com/nielslange/smntcs-quantity-buttons-for-woocommerce/pull/68/commits/48790455f8196cd6dd07c07637612bd3bfe9165c

but still not working

**Comment by icepunk** [comment]
i changed this line:
[ plugin > button-handler.js ]
var quantities = document.querySelectorAll( '.product-quantity > .quantity ');

to 

var quantities = document.querySelectorAll( ' .quantity ');

and its work.

**Comment by nielslange** [comment]
Closing in benefit of https://github.com/nielslange/smntcs-quantity-buttons-for-woocommerce/issues/67.
